### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#10]
See file liv_000002, page 0104.

I have no idea what's going on here, but part of a line is way off the page.

Also see file liv_000004, page 0074 for some other words that go beyond the left margin, whose behavior I don't understand.

**Comment by jamescummings** [comment]
@awisnicki Can you double check this and maybe send me a screenshot.  I can see that (in liv_000004) that the word 'Malumba' is left aligned but is still on the page.  It is encoded as in an 'add' element. Maybe that is doing it.  I saw nothing wrong in liv_000002 page 0104 though.

**Comment by awisnicki** [comment]
Whoops, sorry, the correct file is liv_000003, page 104 (not what I put above). In this case and in liv_000004, page 74 (which is correct above, as you note), I see that the issues seems to be an <add> inside and <item>:

`<lb/><item><placeName><region>West</region></placeName></item><item> <add rend="blue"><hi rend="underline"><placeName><settlement type="village">Molsamba</settlement></placeName></hi></add></item>`

**Comment by jamescummings** [comment]
Confirmed. Where there is an `<add>` element it is going off too far to the left.  Fixing by just making add elements be inline instead. (Let me know if you want something different, like italic or surrounded by [ ] or something.)

**Comment by awisnicki** [comment]
This looks good except there should be a space between the added item and the item directly to the left. Right now in the pdf we have:

WestMolsamba

whereas in the XML, on page `<pb facs="liv_000004_0074" n="0074"/>`, it is:

`<lb/><item><placeName><region>West</region></placeName></item><item> <add rend="blue"><hi rend="underline"><placeName><settlement type="village">Molsamba</settlement></placeName></hi></add></item>`

So the final rendering should be:

West Molsamba

i.e., a space between the two words.

**Comment by jamescummings** [comment]
I believe I've now fixed this by adding a space before all adds. Close if so.

**Comment by awisnicki** [comment]
Unfortunately, this does too much. A lot of adds now have two spaces before, but worse sometimes when letters are added in the middle of word, there's now a space in the middle of the word. Any other paths to solving this?

**Comment by jamescummings** [comment]
I've tried to fix this, I now only add the space before `<add>` if it is not inside a `<subst>`.

**Comment by awisnicki** [comment]
Yes, I think we can call it a wrap on this. Thanks very much.
