### ISSUE TITLE
spaces between items

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#13]
When we have two items in a row, please put one space between them. On page liv_000004_0083: 

`<item><measure>2</measure> -</item><item><placeName><settlement type="village"><persName>Chirombe</persName>'s</settlement></placeName></item>`

Should appear as:

2 - Chirombe's

Right now it appears: 

2 -Chirombe's

(Note the space after the dash is missing.)

**Comment by jamescummings** [comment]
I believe I've now fixed this by adding a space before all items. Close if so.

**Comment by awisnicki** [comment]
Yes, good. Thank you!
