### ISSUE TITLE
Linebreaks between <front> and <body>; Page breaks between <body> and <back>

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#2]
See file liv_000001 for this

Page 0003 is the last page of `<front>` and 0004 is the first page of `<body>`. We need a line break between these as we have been pages in `body`

---

The break between `<body>` and `<back>` should work the same way. One empty line between the two. Right now, when the `<back>` tag appears it puts it on a whole new page. See the transition between page 0109 and 0110 for an example of this.

**Comment by jamescummings** [comment]
If I've understood correctly, fixing by adding a couple line breaks at beginning of body and changing pagebreak at beginning of back to a couple line breaks.

**Comment by awisnicki** [comment]
Looks good except page break at beginning of back would probably do with one or two line breaks (right now there are circa 4-5 line breaks there).

**Comment by jamescummings** [comment]
This comes because of the nature of the div and body formatting.  I don't think I can fix this easily. Though I've done what I can to reduce the number of line breaks there.

**Comment by awisnicki** [comment]
I think this is good. Let's call it a wrap on this one. Thank you!
