### ISSUE TITLE
<pb> followed by <p rend="no-indent">

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#3]
See file liv_000001

Currently, when `<pb>` is followed by `<p rend='no-indent'>` an empty line is inserted between the two. This needs to be removed. See pages 0006 and 0016 for examples of this.

The empty line above `<p rend='no-indent'>` also occurs when this tag appears in the middle of a paragraph. See page 0008 for an example of this

**Comment by jamescummings** [comment]
Fixing by testing on pb match for second following sibling (since almost always seems to be linebreak then paragraph). Seems to work at first glance but may produce unexpected results elsewhere.

**Comment by jamescummings** [comment]
Believe this is done, close if ok.

**Comment by awisnicki** [comment]
This is fixed, but one more minor tweak needed. Please add one linebreak before a page break. So, in other words, just before a new page appears signaled by a number in square brackets, add one line break above that. Therefore, there will be two line breaks before the page number and one after (right now there is one before and one after).

**Comment by jamescummings** [comment]
I believe I've now fixed this.

**Comment by awisnicki** [comment]
Definitely fixed. Thank you!
