### ISSUE TITLE
<milestone>

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#4]
See file liv_000001

`<lb/><milestone unit='section' rend='line'>` and variants thereof are not showing up in any way. We have lines, half lines, quarter lines, double lines and triple lines. 

It'd be nice to render these. If it's going to prove too difficult, however, then at least turn off the `<lb>` and `<milestone>` as together they kick in two blank lines etc.

For an example see page 0025

**Comment by jamescummings** [comment]
When you say render these... in what way? I will for now just put a short rule across when there is a milestone of any sort, but I could put different lengths and multiple lines for the different rend values if you want.  If so I would assume:
* line = half way across PDF page (say 20em) 
* half-line = 10em length
* quarter-line = 5em length
* double-line = 20em but 2 of them
* triple-line = 20em but 3 of them

**Comment by awisnicki** [comment]
Let's go with these lenghts:

line: 18em

double-line: 18em but two of them

triple-line: 18em but three of them

half-line: 15em (not seeing this render yet, see liv_000001_0083 for an example of where this should be)

quarter-line: 12em (not seeing this render yet, see liv_000001_0094 for an example of where this should be)

**Comment by jamescummings** [comment]
I believe I've done this values added as numerical length: line=200, half-line=100, quarter-line=50
Close if ok.

**Comment by awisnicki** [comment]
Looks good -- a wrap. Thank you!
