### ISSUE TITLE
<note>

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#5]
`<note>` is acting very wonky and is kicking in multiple blank lines above and below as well as indenting. Please simply render it in place as is.

**Comment by jamescummings** [comment]
Fixed making notes just become inline text. Let me know if you want to distinguish them in any way.

**Comment by awisnicki** [comment]
Please put them in square brackets [] and please put them on their own line as relevant. Right now, if a `<note>` appears on its own line, it is actually being put at the end of the preceding line. See the note near the end of liv_000001_0078 for an example of this.

**Comment by jamescummings** [comment]
I believe I'ved fixed this by putting notes in square brackets and starting a newline before and after them.

**Comment by awisnicki** [comment]
Almost there. An extra line break is being kicked in after the note, so (liv_000001, page 0069):

dollars
[10th]

Bought another camel

Should become:

dollars
[10th]
Bought another camel

**Comment by jamescummings** [comment]
I believe I've now fixed this.

**Comment by awisnicki** [comment]
Yes, looks good. Thank you!
