### ISSUE TITLE
<list> and <table>

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#6]
See file liv_000001

The `<list>` and `<item>` tags add a bunch of mods we don't need. See page page 0079 for an example. We don't need items in lists to:

1. Start with a bullet point
2. Be indented
3. Have blank lines above and below them

A list like the one on page 0079 should come out something like the following:

5 bags of beads
5 boxes instruments
books
clothes -

rather than the way it's currently rendering.

------

`<table>`, `<row>` and `<cell>` need the exact same tweaks except that these don't have the bullet point, but they are indented and have extra empty lines above and below. See page 0083 for an example.

**Comment by jamescummings** [comment]
Lists/items: Fixed by stopping lists and items being dealt with as such, now just new lines. 
Tables: I assume you mean you that you don't want the extra lines between rows.  Removed those by suppressing them.

**Comment by awisnicki** [comment]
Yes, all looks good except it looks like `<table>` is kicking out an extra linebreak afterwards. So, for instance, on liv_000001_0083 after the table but before the milestone, there is an extra empty line where there needn't be.

**Comment by jamescummings** [comment]
I've tried to do what I can on this one but built-in rules in latex about tables and paragraphs make reducing this space more hard. You could remove the lb element after any table if you still think it looks wrong. But otherwise, close if you think it looks a bit better.

**Comment by awisnicki** [comment]
OK, I'll see if I can tackle this another way and let's call it a wrap on this. Thanks very much!
