### ISSUE TITLE
<list> to <pb/>

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#8]
See file liv_000002 for this

When a `<list>` is followed by a `<pb/>` please ensure that an extra line-break is needed. See pages 0086 to 0087 for this. 

I haven't yet found an example of this, but probably the same thing will be needed for `<table>` followed by `<pb/>`

**Comment by jamescummings** [comment]
I've added a couple newlines after lists where the second following element is a pb.

**Comment by awisnicki** [comment]
Looks good, but it appears that you've put in two linebreaks after one whereas one would do.

**Comment by jamescummings** [comment]
I have removed a newline from this. If ok, close issue.

**Comment by awisnicki** [comment]
Yes, looks good. Thank you!
