### ISSUE TITLE
<figure><head>

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/PDF-Files#9]
See file liv_000002

When `<head>` appears within `<figure>`, the rendering is wonky with the text being indented/centered and extra empty lines being added above and below. See page 0015 for an example of this.

**Comment by jamescummings** [comment]
I believe I've fixed this.

**Comment by awisnicki** [comment]
Well you've turned off head (not correct) and `<figDes>` which also appears within `<figure>` is now being tacked onto the preceding line. So, for instance, in liv_000002_0021 we have:

yet[Geographical calculation.]

whereas it should be:

yet
12th [Geographical calculation.]

(note: the "12th" appears within `<head>`)

**Comment by jamescummings** [comment]
I believe I've now fixed this by adding a newline after head and including head. Close if so.

**Comment by awisnicki** [comment]
Not quite right. No new line after head needed if it's not already in the XML. New line *before* `<figure><head>` should be instituted if there's an `<lb/>` preceding. So right now, for liv_000002_0021 (for instance), you've got:

yet 12th
[Geographical calculation.]

Whereas it should be rendering:

yet
12th [Geographical calculation.]

**Comment by jamescummings** [comment]
I believe I have now fixed this.

**Comment by awisnicki** [comment]
Indeed, fixed. Thanks again!
